clean up the autosubmit approach

diff --git a/.github/workflows/daily-dev-bump.yaml b/.github/workflows/daily-dev-bump.yaml
--- a/.github/workflows/daily-dev-bump.yaml
+++ b/.github/workflows/daily-dev-bump.yaml
@@ -108,23 +108,25 @@ jobs:
 
 
 
-          if [ "$UPDATE_TYPE" == "release" ]; then
-            # Since this is a release PR then don't autosubmit it.
-            FLAGS=""
-          else
+          # Add the autosubmit label if it was specified, or if this is a scheduled event.
+          if ["$AUTOSUBMIT" == "true" ] || [ "$IS_SCHEDULED" == "true" ]; then
+            if [ "$UPDATE_TYPE" == "release" ]; then
+              echo "ERROR: Auto submitting a release PR is not allowed"
+              exit 1
+            fi
             FLAGS="--add-label=autosubmit"
+          else
+            FLAGS=""
           fi
 
           if [ "$IS_DRY_RUN" != "true" ] ; then
             PR_URL=$(gh pr create --title "$COMMIT_MESSAGE" --body "RELEASE_NOTE_EXCEPTION=Automated Version Bump")
             
-            # Add the autosubmit label if it was specified, or if this is a scheduled event.
-            if [ "$AUTOSUBMIT" == "true" ] || [ "$IS_SCHEDULED" == "true" ]; then
-              # Change github credentials back to the actions bot.
-              GH_TOKEN="$ORIGINAL_GH_TOKEN"
 
-              gh pr edit $PR_URL $FLAGS
-            fi
+            # Change github credentials back to the actions bot.
+            GH_TOKEN="$ORIGINAL_GH_TOKEN"
+
+            gh pr edit $PR_URL $FLAGS
           fi
 
         env:
