check autosubmitting release PRs before creating the PR

diff --git a/.github/workflows/daily-dev-bump.yaml b/.github/workflows/daily-dev-bump.yaml
--- a/.github/workflows/daily-dev-bump.yaml
+++ b/.github/workflows/daily-dev-bump.yaml
@@ -106,6 +106,10 @@ jobs:
           git commit -a -m "$COMMIT_MESSAGE"
           git push -u origin "$BRANCH_NAME"
 
+          if [ "$UPDATE_TYPE" == "release" ] && [ "$AUTOSUBMIT" == "true" ]; then
+            echo "ERROR: Auto submitting a release PR is not allowed"
+            exit 1
+          fi
 
           if [ "$IS_DRAFT" == "true" ]; then
             CREATION_FLAGS="--draft"
@@ -115,10 +119,6 @@ jobs:
 
           # Add the autosubmit label if it was specified, or if this is a scheduled event.
           if [ "$AUTOSUBMIT" == "true" ] || [ "$IS_SCHEDULED" == "true" ]; then
-            if [ "$UPDATE_TYPE" == "release" ]; then
-              echo "ERROR: Auto submitting a release PR is not allowed"
-              exit 1
-            fi
             # Change github credentials back to the actions bot.
             GH_TOKEN="$ORIGINAL_GH_TOKEN"
 
