renaming

diff --git a/.github/workflows/release-preparedness.yaml b/.github/workflows/release-preparedness.yaml
--- a/.github/workflows/release-preparedness.yaml
+++ b/.github/workflows/release-preparedness.yaml
@@ -4,8 +4,9 @@ on:
   pull_request:
 
 jobs:
-  check-release-condition:
+  releas-preparedness:
     runs-on: ubuntu-latest
+    name: Release Preparedness
     steps:
 
       - name: Get Pull Request Number
@@ -43,6 +44,17 @@ jobs:
           echo "HAS_EXCEPTION_LABEL: $HAS_EXCEPTION_LABEL"
 
           echo "::set-output name=HAS_EXCEPTION_LABEL::$HAS_EXCEPTION_LABEL"
+      - name: Check Release Preparedness requirements
+        env:
+          HAS_CHANGED_RELEASE_NOTES: ${{steps.get-modified-files.outputs.HAS_CHANGED_RELEASE_NOTES}}
+          HAS_EXCEPTION_LABEL: ${{steps.get-label-exception.outputs.HAS_EXCEPTION_LABEL}}
+        run: |
+          if [ "$HAS_CHANGED_RELEASE_NOTES" != "true" ] || [ "$HAS_EXCEPTION_LABEL" != "true" ] ; then
+            echo "Release Preparedness check failed"
+            echo "::error file=packages/devtools_app/lib/src/framework/release_notes/release_notes.json,line=0,col=0,endColumn=0,title='Release Preparedness check failed'::If your change is user facing, add a release note. Otherwise add the 'Not User Facing' label to your PR"
+            exit 1
+          fi
+
       - name: Check Release Preparedness requirements
         env:
           HAS_CHANGED_RELEASE_NOTES: ${{steps.get-modified-files.outputs.HAS_CHANGED_RELEASE_NOTES}}
