Solidify the code to delete all DartDevtoolWorkflowBot branches that are closed

diff --git a/.github/workflows/workflow-bot-cleanup.yaml b/.github/workflows/workflow-bot-cleanup.yaml
--- a/.github/workflows/workflow-bot-cleanup.yaml
+++ b/.github/workflows/workflow-bot-cleanup.yaml
@@ -24,20 +24,32 @@ jobs:
             README.md
       - name: Clean up branches
         run: |
-          set -ex
+          set -e
 
           # Get list of branches that exist on the remote, then filter for the workflow bot branches
           EXISTING_BRANCHES=$(git ls-remote --heads | grep refs/heads | awk  '{print $2}' |sed 's|refs/heads/\(.*\)$|\1|')
           for EXISTING_BRANCH in $EXISTING_BRANCHES; do
-            PR_IS_CLOSED=$(gh pr view --json closed --jq '.closed' "$EXISTING_BRANCH")
-            PR_AUTHOR=$(gh pr view --json author --jq '.author.login' "$EXISTING_BRANCH")
-            if [[ "$PR_IS_CLOSED" == "true" && "$PR_AUTHOR" == "DartDevtoolWorkflowBot" ]]; then
-              # If the branch exists, DartDevtoolWorkflowBot is the author and the PR is closed we will delete it
+            set +e # Turn off exit on error, since "gh pr view" may fail if branch doesn't exist
+            PR_INFO=$(gh pr view --json closed,author "$EXISTING_BRANCH")
+            if [[ $? -ne 0 ]]; then
+              # If getting PR_INFO fails assume the PR does not exist
+              echo "SKIP: No PR exists for $EXISTING_BRANCH"
+              continue
+            fi
+            set -e # Turn exit on error back on
+
+            PR_IS_CLOSED=$(echo $PR_INFO | jq -r '.closed')
+            PR_AUTHOR=$(echo $PR_INFO | jq -r '.author.login')
+            if [[ "$PR_IS_CLOSED" == "true" ]] && [[ "$PR_AUTHOR" == "DartDevtoolWorkflowBot" ]]; then
+              # Delete branches where:
+              # - DartDevtoolWorkflowBot is the author 
+              # - the PR is closed
               echo "Deleting $EXISTING_BRANCH"
               echo "gh api  /repos/flutter/devtools/git/refs/heads/$EXISTING_BRANCH -X DELETE"
             else
-              echo "Avoiding $EXISTING_BRANCH with is_closed:$PR_IS_CLOSED and author:$PR_AUTHOR"
+              echo "SKIP: Avoiding $EXISTING_BRANCH { is_closed:$PR_IS_CLOSED, author:$PR_AUTHOR }"
             fi
           done
+
         env:
           GH_TOKEN: ${{ secrets.DEVTOOLS_WORKFLOW_BOT_TOKEN }}
